/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PalsIndexImport } from './routes/pals/index'
import { Route as PalsPalsIdIndexImport } from './routes/pals/$palsId/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PalsIndexRoute = PalsIndexImport.update({
  id: '/pals/',
  path: '/pals/',
  getParentRoute: () => rootRoute,
} as any)

const PalsPalsIdIndexRoute = PalsPalsIdIndexImport.update({
  id: '/pals/$palsId/',
  path: '/pals/$palsId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/pals/': {
      id: '/pals/'
      path: '/pals'
      fullPath: '/pals'
      preLoaderRoute: typeof PalsIndexImport
      parentRoute: typeof rootRoute
    }
    '/pals/$palsId/': {
      id: '/pals/$palsId/'
      path: '/pals/$palsId'
      fullPath: '/pals/$palsId'
      preLoaderRoute: typeof PalsPalsIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pals': typeof PalsIndexRoute
  '/pals/$palsId': typeof PalsPalsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pals': typeof PalsIndexRoute
  '/pals/$palsId': typeof PalsPalsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pals/': typeof PalsIndexRoute
  '/pals/$palsId/': typeof PalsPalsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/pals' | '/pals/$palsId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/pals' | '/pals/$palsId'
  id: '__root__' | '/' | '/about' | '/pals/' | '/pals/$palsId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PalsIndexRoute: typeof PalsIndexRoute
  PalsPalsIdIndexRoute: typeof PalsPalsIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PalsIndexRoute: PalsIndexRoute,
  PalsPalsIdIndexRoute: PalsPalsIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/pals/",
        "/pals/$palsId/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/pals/": {
      "filePath": "pals/index.jsx"
    },
    "/pals/$palsId/": {
      "filePath": "pals/$palsId/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
